fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    # multiple hooks:
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^notebooks
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    # after repo comments should be skipped
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/prettier/pre-commit
    # weird case where rev version is not immediately after repo url
    # also, the revision are branch names, not tags
    hooks:
      - id: prettier
        exclude: ^notebooks
    rev: v2.1.2
